config/routes.rb
Rails.application.routes.draw do
  root 'upload_files#index'
  devise_for :users
  get 'upload_files/index', as: 'user_root'
  resources :upload_files, only: [:show, :create, :index, :destroy], path: '' do
    member do
      get 'download'
    end
  end
  get 'debug/delete_all_files'
  get 'debug/delete_all_users'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all

    else user.user?
      can :read, :all
      can :create, UploadFile
      can :download, UploadFile
      can :destroy, UploadFile do |f|
        f.try(:user) == user
      end
    end
  end
end

app/models/upload_file.rb
class UploadFile

  include Mongoid::Document
  include Mongoid::Paperclip

  belongs_to :user
  field :content, type: String, default: ""

  has_mongoid_attached_file :attachment,
   path: "#{Rails.root}/public/attachments/:id.:extension"

  
  validates :content, length: { maximum: 120 }

  validates :attachment, attachment_presence: true
  validates_with AttachmentSizeValidator, attributes: :attachment, less_than: 10.megabytes
  do_not_validate_attachment_file_type :attachment

end

app/models/user.rb
class User
  include Mongoid::Document
  has_many :upload_files

  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  ## Database authenticatable
  field :email,               type: String, default: ""
  field :encrypted_password,  type: String, default: ""

  ## Rememberable
  field :remember_created_at, type: Time
  field :role,                type: String, default: "user"

  def admin?
    role == 'admin'
  end

  def user?
    role == 'user'
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to new_user_session_path
  end

  rescue_from Mongoid::Errors::DocumentNotFound do |exception|
    redirect_to new_user_registration_path
  end

  def current_user
    super || guest_user
  end

  def guest_user
    User.find(session[:guest_user_id].nil? ? session[:guest_user_id] = create_guest_user.id : session[:guest_user_id])
  end

  def create_guest_user
    user = User.new()
    user.save(validate: false)
    user
  end

end

app/controllers/debug_controller.rb
class DebugController < ApplicationController

  def delete_all_files
    UploadFile.delete_all
    redirect_to root_path
  end

  def delete_all_users
    User.delete_all
    redirect_to root_path
  end

end

app/controllers/upload_files_controller.rb
 class UploadFilesController < ApplicationController
  load_and_authorize_resource
  before_action :set_upload_file, only: [:show, :download]

  def index
    @upload_files = UploadFileDecorator.decorate_collection(UploadFile.order('attachment_updated_at desc'))
    @upload_file = UploadFile.new
  end

  def create
    @upload_file = current_user.upload_files.build(upload_file_params)
    respond_to do |format|
      if @upload_file.save
        format.js
        format.html { redirect_to upload_files_path, notice: 'Upload file was successfully created.' }
      else
        format.js
        format.html { redirect_to upload_files_path, alert: @upload_file.errors.full_messages.join(", ") }
      end
    end
  end

  def show
  end

  def destroy
    @upload_file.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to upload_files_url, notice: 'Upload file was successfully destroyed.' }
    end
  end

  def download
    send_file @upload_file.get_attach_path
  end

  private
    def set_upload_file
        @upload_file = UploadFile.find(params[:id]).decorate
    end

    def upload_file_params
      params.require(:upload_file).permit(:content, :attachment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "MongoShara"
    if page_title.empty?
      base_title
    else
    "#{base_title} | #{page_title}"
    end
  end
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>RGhost — file sharing</title>
  <meta content="Free file hosting without waiting and captcha. Preview for images, media, documents and archives. RGhost — fast and easy file sharing." name="description" />
  <meta content="file exchange, free file exchange, best file exchange, fast file exchange, file hosting, file storage, file sharing, image hosting, fotohosting, videohosting, audiohosting, share file, share image, review files, preview" name="keywords" />
  <meta charset="utf-8">
  <meta content="IE=edge" http-equiv="X-UA-Compatible">
  <meta content="width=device-width, initial-scale=1" name="viewport">
  <meta content="authenticity_token" name="csrf-param" />
  <meta content="JcT72epN09b4apyPRJ57MfBLGbZ1CyOD/i/3ZW6QdME=" name="csrf-token" />
  <link href="/assets/stylesheets/first.css" media="screen" rel="stylesheet" type="text/css" />

  <link href="/opensearch_en.xml" rel="search" title="rghost" type="application/opensearchdescription+xml">
  <link href="/favicon.ico" rel="shortcut icon" sizes="16x16 32x32 48x48 64x64" type="image/vnd.microsoft.icon" />
  <link href="/favicon.ico" rel="icon" sizes="196x196">


  <!--[if lt IE 9]>
  <script src="/assets/html5_ie-875f0d42a52ff5536404da8fda8d423b.js" type="text/javascript"></script>
  <![endif]-->
</head>
<body class="with-top-navbar" id="welcome___index">
<div class="with-bg wrapper">

  <nav class="navbar navbar-inverse navbar-fixed-top app-navbar">
    <div class="container">
      <div class="navbar-header">
        <button class="navbar-toggle collapsed" data-target="#navbar-collapse-main" data-toggle="collapse" type="button">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="/" class="brand" title="RGhost — file sharing"><img alt="Logo" height="50px" onerror="this.onerror=null; this.src=&#x27;/logo.png&#x27;" src="/assets/logo.svg" width="150px" /></a>
      </div>
      <div class="navbar-collapse collapse" id="navbar-collapse-main">
        <form accept-charset="UTF-8" action="/search" class="navbar-form navbar-right app-search hidden-sm" method="get" role="search"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" /></div>
          <div class="form-group">
            <input class="form-control" data-action="grow" name="s" placeholder="Search" type="text">
          </div>
        </form>

        <ul class="nav navbar-nav navbar-right hidden-xs">
          <li><a href="#registerModal" data-target="#registerModal" data-toggle="modal" title="Get free account">Sign up</a></li>
          <li><a href="#signInModal" data-target="#signInModal" data-toggle="modal">Sign in</a></li>
        </ul>
        <ul class="nav navbar-nav hidden-sm hidden-md hidden-lg">
          <li><a href="#registerModal" data-target="#registerModal" data-toggle="modal" title="Get free account">Sign up</a></li>
          <li><a href="#signInModal" data-target="#signInModal" data-toggle="modal">Sign in</a></li>
        </ul>
      </div>
    </div>
  </nav>


  <div class="container" id="content">

    <div class="container-fill-height">
      <div class="container-content-middle">
        <div class="row">
          <div class="m-x-auto">
            <%= image_tag("cloud-storage.svg", alt: "Cloud-storage", class: "img-responsive center-block cloud-img")%>
          </div>
        </div>
        <div class="upload-form-wrap">
          <center>
            <button class="btn btn-primary btn-upload" id="upload_button" name="button" type="submit">Share - select a file</button>
<span class="hint hint-upload no-overflow nowrap">
Maximum file size is
100 MB
</span>
            <div id="upload-error" style="display: none;"></div>
            <form accept-charset="UTF-8" action="http://muonium.rghost.net/files" class="form-inline height-0" enctype="multipart/form-data" id="upload_form" method="post"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" /><input name="authenticity_token" type="hidden" value="JcT72epN09b4apyPRJ57MfBLGbZ1CyOD/i/3ZW6QdME=" /></div>
              <div class="form-group">
                <input id="choose" name="file" size="50" type="file" />
              </div>
              <input class="btn btn-primary upload" id="commit" name="commit" type="submit" value="Upload" />
            </form>

            <div class="upload-progress-container" data-max-file-size="104857600" data-status-url="http://muonium.rghost.net/progress" data-upload-progress-for="upload_form" style="display:none"></div>
            <div class="m-x-auto">
              <div class="upload-info hide-element">
                <div class="row">
                  <div class="progress progress-striped active upload-progress hide-element">
                    <div aria-valuemax="100" aria-valuemin="0" aria-valuenow="0" class="progress-bar" role="progressbar">
                      0%
                    </div>
                  </div>
                  <button class="btn btn-danger btn-xs btn-upload-cancel hide-element" type="button">
                    <span class="icon icon-circle-with-cross"></span>
                  </button>
                </div>
<span class="hint hint-upload-progress nowrap no-overflow">
Starting...
</span>
              </div>
            </div>
          </center>
          <div id="dropbox">
            <div class="dropbox-info">
<span class="dropbox-info-text">
Drop the file wherever you feel like, and we'll upload it for you!
</span>
              <br>
<span class="dropbox-info-hint">
Maximum file size is
100 MB
</span>
            </div>
          </div>

        </div>
        <div class="row hidden-xs shadow flex">
          <div class="m-x-auto">
            <div class="text-block-main m-t-md">
              <p>
<span class="icon icon-copy">
 You can drag and drop a file on this page
</span>
              </p>
              <p>
<span class="icon icon-cloud">
 Or select a file repository in the cloud
</span>
              </p>
            </div>
          </div>
        </div>
        <div class="cloud-icons shadow">
          <div class="row text-center">
            <ul class="list-inline">
              <li>
                <a href="#" class="link-button" data-remote="true"><div class="icon-dropbox"></div>
                  <div class="hint hint-hover">Dropbox</div>
                </a></li>
              <li>
                <a href="#" class="link-button" data-remote="true"><div class="icon-google"></div>
                  <div class="hint hint-hover">Google Drive</div>
                </a></li>
              <li>
                <a href="#" class="link-button" data-remote="true"><div class="icon-onedrive"></div>
                  <div class="hint hint-hover">Onedrive</div>
                </a></li>
            </ul>
          </div>
        </div>
        <script data-app-key="sx0b6jakttt9di5" id="dropboxjs" src="https://www.dropbox.com/static/api/2/dropins.js" type="text/javascript"></script>

        <script src="https://apis.google.com/js/api.js?onload=onApiLoad" type="text/javascript"></script>
        <div id="result-google"></div>

        <script client-id="000000004C177A0E" id="onedrive-js" src="https://js.live.net/v5.0/OneDrive.js" type="text/javascript"></script>

      </div>
    </div>

  </div>
  <div class="push"></div>
</div>

<div aria-hidden="true" aria-labelledby="msgModal" class="modal fade" id="signInModal" role="dialog" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <form accept-charset="UTF-8" action="/profile/sign_in" class="simple_form form-horizontal" method="post"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" /><input name="authenticity_token" type="hidden" value="JcT72epN09b4apyPRJ57MfBLGbZ1CyOD/i/3ZW6QdME=" /></div><div class="modal-header">
        <button aria-hidden="true" class="close" data-dismiss="modal" type="button">×</button>
        <h4 class="modal-title">Sign in</h4>
      </div>
        <div class="modal-body">

          <div class="form-group email required user_email"><div class="col-xs-4 col-sm-3 control-label"><label class="email required" for="user_email"><abbr title="required">*</abbr> Email</label></div><div class="col-xs-8 col-sm-9"><input class="string email required form-control form-control" id="user_email" name="user[email]" required="required" size="50" type="email" value="" /></div></div>
          <div class="form-group password required user_password"><div class="col-xs-4 col-sm-3 control-label"><label class="password required" for="user_password"><abbr title="required">*</abbr> Password</label></div><div class="col-xs-8 col-sm-9"><input class="password required form-control" id="user_password" name="user[password]" required="required" size="50" type="password" /><p class="help-block"><a href="/profile/password/new">Forgot password?</a></p></div></div>
          <div class="on-top-20">
            <div class="form-group boolean optional user_remember_me"><div class="col-sm-offset-3 col-sm-9"><div class="checkbox"><input name="user[remember_me]" type="hidden" value="0" /><label class="checkbox"><input checked="checked" class="boolean optional" id="user_remember_me" name="user[remember_me]" type="checkbox" value="1" />Remember me</label></div></div></div>
          </div>
        </div>
        <div class="modal-footer">
          <div class="row">
            <div class="col-xs-6">
              <div class="text-left">
                <a href="/profile/openid_login" class="btn btn-default">OpenID</a>
              </div>
            </div>
            <div class="col-xs-6">
              <div class="text-right">
                <input class="btn btn-primary" name="commit" type="submit" value="Sign in" />
              </div>
            </div>
          </div>
        </div>
      </form>

    </div>
  </div>
</div>

<div aria-hidden="true" aria-labelledby="msgModal" class="modal fade" id="registerModal" role="dialog" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <form accept-charset="UTF-8" action="/profile" class="simple_form form-horizontal" id="new_user" method="post"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" /><input name="authenticity_token" type="hidden" value="JcT72epN09b4apyPRJ57MfBLGbZ1CyOD/i/3ZW6QdME=" /></div><div class="modal-header">
        <button aria-hidden="true" class="close" data-dismiss="modal" type="button">×</button>
        <h4 class="modal-title">Registration</h4>
      </div>
        <div class="modal-body">

          <div class="form-group string required user_name"><div class="col-xs-4 col-sm-3 control-label"><label class="string required" for="user_name"><abbr title="required">*</abbr> Name</label></div><div class="col-xs-8 col-sm-9"><input class="string required form-control" id="user_name" name="user[name]" required="required" size="50" type="text" /></div></div>
          <div class="form-group email required user_email"><div class="col-xs-4 col-sm-3 control-label"><label class="email required" for="user_email"><abbr title="required">*</abbr> Email</label></div><div class="col-xs-8 col-sm-9"><input class="string email required form-control form-control" id="user_email" name="user[email]" required="required" size="50" type="email" /></div></div>
          <div class="form-group password required user_password"><div class="col-xs-4 col-sm-3 control-label"><label class="password required" for="user_password"><abbr title="required">*</abbr> Password</label></div><div class="col-xs-8 col-sm-9"><input class="password required form-control" id="user_password" name="user[password]" required="required" size="50" type="password" /></div></div>
          <div class="form-group password required user_password_confirmation"><div class="col-xs-4 col-sm-3 control-label"><label class="password required" for="user_password_confirmation"><abbr title="required">*</abbr> Confirm</label></div><div class="col-xs-8 col-sm-9"><input class="password required form-control" id="user_password_confirmation" name="user[password_confirmation]" required="required" size="50" type="password" /></div></div>
        </div>
        <div class="modal-footer">
          <div class="row">
            <div class="col-xs-2">
              <div class="text-left">
                <a href="/profile/openid_login" class="btn btn-default">OpenID</a>
              </div>
            </div>
            <div class="col-xs-10">
              <div class="text-right">
                <input class="btn btn-primary" data-disable-with="Creating…" name="commit" type="submit" value="Sign up" />
              </div>
            </div>
          </div>
        </div>
      </form>

    </div>
  </div>
</div>

<script src="/assets/application-8a372a81ce314721edea2a79e55b4aa7.js" type="text/javascript"></script>




<script type="text/javascript">
  //<![CDATA[
  I18n.defaultLocale = "en"
  I18n.locale = "en"

  //]]>
</script><script>
  var blocks = JSON.parse(atob("e30="));
</script>
</body>
</html>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <p>&copy; MongoShara 2016</p>
</footer>

app/views/layouts/_header.html.erb
<div class="container">
  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <%= link_to "MongoShara", upload_files_path, id: "logo", class:"navbar-brand" %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "All files", upload_files_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Sign out",
             destroy_user_session_path, method: :delete %></li>
           <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Log in", new_user_session_path %></li>
           <% end %>
        </ul>
      </nav>
    </div>
  </header>
</div>

app/views/layouts/_messages.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title (yield(:title))%></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class='container'>
    <%= render 'layouts/header' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

app/views/upload_files/_form.html.erb
<div class="well">
  <%= form_for(@upload_file) do |f| %>
    <p>
      <%= f.label :content %>
    </p>
    <p>
      <%= f.text_area :content, class: 'form-content', rows: 3 %>
    </p>

    <p>
      <label class="btn-sm btn-default btn-file">
      <%= f.file_field :attachment %>
        </label>
    </p>

    <p>
      <%= f.submit 'Upload!', class: 'btn btn-primary' %>
    </p>
  <% end %>
</div>

app/views/upload_files/_upload_file.html.erb
<% @upload_files.each do |upload_file|%>
  <%= upload_file.download_link %> |
  <%= upload_file.size %> |
  <p>
    author: <%= upload_file.author_email %>
    <% if can? :destroy, upload_file %> |
        <%= upload_file.link_to_destroy %>
    <% end %> |
    <%= upload_file.link_to_show %>
  </p>
  <%= upload_file.attach %>
  <h4>
    <%= upload_file.content %>
  </h4>

  <hr>
  <br>
<% end %>

app/views/upload_files/create.js.erb
$(".upload_file").html("<%= j (render 'upload_file') %>")

app/views/upload_files/index.html.erb
<% provide(:title, 'All files') %>
<div class='container'>
<% if Rails.env.development? %>
  <div class="well">
    <%= link_to 'debug delete_all_files', debug_delete_all_files_path, class: 'btn btn-danger' %>
    <%= link_to 'debug delete_all_users', debug_delete_all_users_path, class: 'btn btn-danger' %>
  </div>
<% end %>
<div class='row'>
  <div class='col-md-5'>
  </div>
  <div class='col-md-3'>
    <%= render 'form' %>
  </div>
  <div class='col-md-4'>
  </div>
</div>
<%= render 'upload_file' %>

app/views/upload_files/show.erb
<%= @upload_file.download_link %> |
<%= @upload_file.size %> |
<p>
 author: <%= @upload_file.author_email %>
  <% if can? :destroy, @upload_file %> |
      <%= @upload_file.link_to_destroy %>
  <% end %> |
  <%= @upload_file.link_to_show %>
</p>
<%= @upload_file.attach %>
<h4> <%= @upload_file.content %> </h4>
<hr>
<br>